export const phoneCodeColumns = [
    { label: 'Albania', value: '+355', zh: '阿尔巴尼亚' },
    { label: 'Algeria', value: '+213', zh: '阿尔及利亚' },
    { label: 'Angola', value: '+244', zh: '安哥拉' },
    { label: 'Argentina', value: '+54', zh: '阿根廷' },
    { label: 'Australia', value: '+61', zh: '澳大利亚' },
    { label: 'Austria', value: '+43', zh: '奥地利' },
    { label: 'Bahamas', value: '+1-242', zh: '巴哈马' },
    { label: 'Brazil', value: '+55', zh: '巴西' },
    { label: 'Canada', value: '+1', zh: '加拿大' },
    { label: 'Chile', value: '+56', zh: '智利' },
    { label: 'China', value: '+86', zh: '中国' },
    { label: 'Colombia', value: '+57', zh: '哥伦比亚' },
    { label: 'Costa Rica', value: '+506', zh: '哥斯达黎加' },
    { label: 'Croatia', value: '+385', zh: '克罗地亚' },
    { label: 'Denmark', value: '+45', zh: '丹麦' },
    { label: 'Egypt', value: '+20', zh: '埃及' },
    { label: 'Finland', value: '+358', zh: '芬兰' },
    { label: 'France', value: '+33', zh: '法国' },
    { label: 'Greece', value: '+30', zh: '希腊' },
    { label: 'Hungary', value: '+36', zh: '匈牙利' },
    { label: 'Iceland', value: '+354', zh: '冰岛' },
    { label: 'India', value: '+91', zh: '印度' },
    { label: 'Israel', value: '+972', zh: '以色列' },
    { label: 'Italy', value: '+39', zh: '意大利' },
    { label: 'Japan', value: '+81', zh: '日本' },
    { label: 'Mexico', value: '+52', zh: '墨西哥' },
    { label: 'Netherlands', value: '+31', zh: '荷兰' },
    { label: 'New Zealand', value: '+64', zh: '新西兰' },
    { label: 'Norway', value: '+47', zh: '挪威' },
    { label: 'Pakistan', value: '+92', zh: '巴基斯坦' },
    { label: 'Philippines', value: '+63', zh: '菲律宾' },
    { label: 'Portugal', value: '+351', zh: '葡萄牙' },
    { label: 'Russia', value: '+7', zh: '俄罗斯' },
    { label: 'Singapore', value: '+65', zh: '新加坡' },
    { label: 'South Africa', value: '+27', zh: '南非' },
    { label: 'Switzerland', value: '+41', zh: '瑞士' },
    { label: 'Sweden', value: '+46', zh: '瑞典' },
    { label: 'Thailand', value: '+66', zh: '泰国' },
    { label: 'Turkey', value: '+90', zh: '土耳其' },
    { label: 'Ukraine', value: '+380', zh: '乌克兰' },
    { label: 'United Arab Emirates', value: '+971', zh: '阿联酋' },
    { label: 'United Kingdom', value: '+44', zh: '英国' },
    { label: 'United States', value: '+1', zh: '美国' }
];

// export const chainImgs = {
//     'BTC': ''
// }